### ISSUE TITLE
Using the EKS Resource detector

### ISSUE THREAD

**Issue by christopher-wong** [aws-observability/aws-otel-go#11]
Hi there 👋 

I'm following the docs https://aws-otel.github.io/docs/getting-started/go-sdk#using-aws-eks-resource-detector to setup the EKS Resource detector but am running into some issues.

```
// Instantiate a new EKS Resource detector
eksResourceDetector := new(eks.ResourceDetector)
```

seems to return `nil`.

What's the proper way of instantiating this?

**Comment by bhautikpip** [comment]
I think the docs mentioned the correct way of  instantiating EKS detector. Are you running this on EKS or non EKS environment? 

```
// Instantiate a new EKS Resource detector
eksResourceDetector := new(eks.ResourceDetector)
resource, err := eksResourceDetector.Detect(context.Background())
```

**Comment by bhautikpip** [comment]
Hi @christopher-wong ,

I submitted a fix for EKS [here](https://github.com/bhautikpip/opentelemetry-go-contrib/tree/eks-fix). This should solve the `bad reference` issue. Feel free to test it out from my branch and see if this resolves your issue. Thanks!

**Comment by christopher-wong** [comment]
Fantastic, thanks so much for looking into this. Sorry, I didn't see your earlier comment. I'll give this a try and report back!

**Comment by bhautikpip** [comment]
This fix is rolled out in recent release - https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v0.17.0 so closing this issue. Feel free to open new one if the issue still exists!
