### ISSUE TITLE
Go / Mux context propagation issues with X-Ray

### ISSUE THREAD

**Issue by christopher-wong** [aws-observability/aws-otel-go#12]
Hi there 👋 

I’ve written two HTTP servers in Golang, instrumented with otelmux, deployed to EKS with the aws-otel-collector sidecar. In X-Ray, I see the traces coming in and the services within the service map, but the graph doesn’t look as expected. 

The call flow of my two services is:

`Client -> service a -> service b`

service-a injects it's request context into the outbound request to service-b before making the request.

```go
req, _ := http.NewRequest(http.MethodGet, "http://service-b.aws-otel-eks.svc.cluster.local/work", nil)
ctx, req := otelhttptrace.W3C(r.Context(), req)
otelhttptrace.Inject(ctx, req)
```

Is this the correct way of handling context propagation?

When I initialize my tracer I also do

```go
otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(
  propagation.TraceContext{},
  propagation.Baggage{},
  xray.Propagator{},
))
```

In the X-Ray service map, things don't link up as expected.

<img width="919" alt="Screen-Shot-2021-01-06-at-11 37 00-AM" src="https://user-images.githubusercontent.com/10580086/103942532-8e0c0600-50fe-11eb-9a27-64134d734786.png">

`service-a` shows two arrows to two different `service-b` nodes, along with nodes for all the HTTP headers. 

These `service-b` nodes that are children of `service-a` are yellow indicating an error (no errors occur in making the actual request, returned 200) while a green `service-b` node sits alone without a parent.

As an aside, it's strange that `service-b.aws-otel-eks.svc.cluster.local` and `service-b.aws-otel-eks.svc.cluster.local:80` are separate nodes.

Here's a gist of one of my servers if it's helpful.

https://gist.github.com/christopher-wong/b1b3f149a4ec45196f7b85cbd760b52f

**Comment by anuraaga** [comment]
Hi @christopher-wong - I'm currently trying to reproduce your setup and hope to have more tips shortly.

One point regarding the separate nodes is that service name needs to be set - currently it's falling back to an inferred hostname including the port, but in the future, it will just show up as `unknown` because of this [spec change](https://github.com/open-telemetry/opentelemetry-specification/issues/1346).

Here's an example of setting the service name

https://github.com/aws-observability/aws-otel-go/pull/10/files#diff-ab3659801cd7d2d5fc98b212c6aab5e61ea7cb772bc1b21d1559d2a6df513cdfR163

**Comment by anuraaga** [comment]
Also you may want to check out our playground - I've just started adding go nodes to it, but the Java examples should be fairly complete

https://github.com/aws-observability/aws-otel-playground

Even if you don't run terraform, you'll still get something relatively reasonable showing up for localhost nodes.

You could go through the environment variables set there, for example the peer service mapping here

https://github.com/aws-observability/aws-otel-playground/blob/main/docker-compose.yml#L130

**Comment by bryan-aguilar** [comment]
Closing because stale
