### ISSUE TITLE
Outdated pieces of documentation

### ISSUE THREAD

**Issue by bonclay7** [aws-observability/aws-otel-go#13]
Hello ! 

Thanks for the great documentation to get started with Open Telemetry on AWS. However I've noticed few bits of the documentation being slightly outdated.

**Go context missing**
The first example is missing `context.Context` as the first argument. https://aws-otel.github.io/docs/getting-started/go-sdk#installation-and-configuration

```go
// Create new OTLP Exporter
exporter, err := otlp.NewExporter(
    otlp.WithTLSCredentials(creds), 
    otlp.WithAddress(<INSERT LISTEN ADDRESS HERE>),
)
```

**Packages path**

The ECS, and EKS detectors in the sections [here](https://aws-otel.github.io/docs/getting-started/go-sdk#using-the-aws-ecs-resource-detector) and [here](https://aws-otel.github.io/docs/getting-started/go-sdk#using-aws-eks-resource-detector) are using a package which has been moved from:

- `go.opentelemetry.io/contrib/detectors/ecs` to I believe `go.opentelemetry.io/contrib/detectors/aws/ecs`
- `go.opentelemetry.io/contrib/detectors/eks` to I believe `go.opentelemetry.io/contrib/detectors/aws/eks`

Thanks

**Comment by bonclay7** [comment]
Actually, with `go.opentelemetry.io/otel/exporters/otlp v0.16.0` the NewExporter signature becomes different

**Comment by anuraaga** [comment]
Thanks @bonclay7 - I am wording on updating our integration test app here and will then apply to the docs, sorry for the delay.

https://github.com/aws-observability/aws-otel-go/pull/10

**Comment by bhautikpip** [comment]
documentation fixes here: https://github.com/aws-otel/aws-otel.github.io/pull/81

**Comment by bonclay7** [comment]
Awesome thanks !
