### ISSUE TITLE
Tracing AWS SDK client calls

### ISSUE THREAD

**Issue by bonclay7** [aws-observability/aws-otel-go#14]
Hi ! 

Moving from instrumenting with X-Ray, I was wondering if there was any support for automatic tracing around AWS SDK like the following example

```go
svc := secretsmanager.New(session.New(&aws.Config{Region: aws.String(region)}))
xray.AWS(svc.Client)
ctx, seg := xray.BeginSegment(context.Background(), "payforadoptions")

res, err := svc.GetSecretValueWithContext(ctx, &secretsmanager.GetSecretValueInput{
	SecretId: aws.String(secretID),
})
seg.Close(nil)
```

![image](https://user-images.githubusercontent.com/10175027/105751310-1f280d00-5f46-11eb-8145-a3c0e6e39b96.png)

Thanks

**Comment by bhautikpip** [comment]
Hi @bonclay7 ,

Thanks for opening up an issue. We currently don't support Tracing AWS SDK client calls for AWS OTel Go. I will mark this issue as a feature request and I would also recommend you to create an issue in [Upstream Open Telemetry Go Contrib  Repo](https://github.com/open-telemetry/opentelemetry-go-contrib) as well.

**Comment by bonclay7** [comment]
Thanks ! I saw this feature request open there as well https://github.com/open-telemetry/opentelemetry-go-contrib/issues/81

**Comment by bhautikpip** [comment]
AWS SDK v2 support is released in upstream OTel Go repo: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/621 so closing this issue.
